[build-system]
requires = [
    "scikit-build-core[pyproject]==1.0.3",
    "pybind11==3.0.4",
    "setuptools==83.0.0",
    "wheel==0.45.1",
]
build-backend = "scikit_build_core.build"

[project]
name = "capio-calf"
dynamic = ["version"]
description = "CAPIO Logging Facility"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
authors = [
    { name = "Marco Edoardo Santimaria", email = "marcoedoardo.santimaria@unito.it" },
]

[project.optional-dependencies]
test = ["pytest>=8.0"]

[project.urls]
Repository = "https://github.com/High-Performance-IO/CALF"
Issues = "https://github.com/High-Performance-IO/CALF/issues"

[tool.scikit-build]
cmake.version = ">=3.16"

[tool.scikit-build.wheel.packages]
"calf" = "bindings/calf"

[tool.scikit-build.cmake.define]
CALF_BUILD_PYTHON_BINDINGS = true
CALF_PROTOBUF = false

[[tool.dynamic-metadata]]
provider = "scikit_build_core.metadata.regex"
field = "version"
input = "CMakeLists.txt"
regex = "(?m)VERSION\\s+(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
result = "{major}.{minor}.{patch}"
