# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calf/protobuf/calf_trace.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calf/protobuf/calf_trace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63\x61lf/protobuf/calf_trace.proto\x12\ncalf.proto\"\xe9\x01\n\x0bTraceRecord\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x04\x12\x10\n\x08scope_id\x18\x02 \x01(\x04\x12\x17\n\x0fparent_scope_id\x18\x03 \x01(\x04\x12*\n\x04kind\x18\x04 \x01(\x0e\x32\x1c.calf.proto.TraceRecord.Kind\x12\x0f\n\x07invoker\x18\x05 \x01(\t\x12\x0c\n\x04\x66ile\x18\x06 \x01(\t\x12\x0c\n\x04line\x18\x07 \x01(\r\x12\x0c\n\x04\x61rgs\x18\x08 \x01(\t\"2\n\x04Kind\x12\x0f\n\x0bSCOPE_ENTER\x10\x00\x12\t\n\x05\x45VENT\x10\x01\x12\x0e\n\nSCOPE_EXIT\x10\x02\"5\n\tTraceFile\x12(\n\x07records\x18\x01 \x03(\x0b\x32\x17.calf.proto.TraceRecordb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calf.protobuf.calf_trace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACERECORD']._serialized_start=47
  _globals['_TRACERECORD']._serialized_end=280
  _globals['_TRACERECORD_KIND']._serialized_start=230
  _globals['_TRACERECORD_KIND']._serialized_end=280
  _globals['_TRACEFILE']._serialized_start=282
  _globals['_TRACEFILE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
