// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calf/protobuf/calf_trace.proto
// Protobuf C++ Version: 6.31.1

#ifndef calf_2fprotobuf_2fcalf_5ftrace_2eproto_2epb_2eh
#define calf_2fprotobuf_2fcalf_5ftrace_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_calf_2fprotobuf_2fcalf_5ftrace_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_calf_2fprotobuf_2fcalf_5ftrace_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_calf_2fprotobuf_2fcalf_5ftrace_2eproto;
}  // extern "C"
namespace calf {
namespace proto {
enum TraceRecord_Kind : int;
extern const uint32_t TraceRecord_Kind_internal_data_[];
class TraceFile;
struct TraceFileDefaultTypeInternal;
extern TraceFileDefaultTypeInternal _TraceFile_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TraceFile_class_data_;
class TraceRecord;
struct TraceRecordDefaultTypeInternal;
extern TraceRecordDefaultTypeInternal _TraceRecord_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TraceRecord_class_data_;
}  // namespace proto
}  // namespace calf
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::calf::proto::TraceRecord_Kind_internal_data_>
    internal::EnumTraitsImpl::value<::calf::proto::TraceRecord_Kind>;
}  // namespace protobuf
}  // namespace google

namespace calf {
namespace proto {
enum TraceRecord_Kind : int {
  TraceRecord_Kind_SCOPE_ENTER = 0,
  TraceRecord_Kind_EVENT = 1,
  TraceRecord_Kind_SCOPE_EXIT = 2,
  TraceRecord_Kind_TraceRecord_Kind_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  TraceRecord_Kind_TraceRecord_Kind_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t TraceRecord_Kind_internal_data_[];
inline constexpr TraceRecord_Kind TraceRecord_Kind_Kind_MIN =
    static_cast<TraceRecord_Kind>(0);
inline constexpr TraceRecord_Kind TraceRecord_Kind_Kind_MAX =
    static_cast<TraceRecord_Kind>(2);
inline bool TraceRecord_Kind_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int TraceRecord_Kind_Kind_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL TraceRecord_Kind_descriptor();
template <typename T>
const ::std::string& TraceRecord_Kind_Name(T value) {
  static_assert(::std::is_same<T, TraceRecord_Kind>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Kind_Name().");
  return TraceRecord_Kind_Name(static_cast<TraceRecord_Kind>(value));
}
template <>
inline const ::std::string& TraceRecord_Kind_Name(TraceRecord_Kind value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TraceRecord_Kind_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool TraceRecord_Kind_Parse(
    ::absl::string_view name, TraceRecord_Kind* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<TraceRecord_Kind>(TraceRecord_Kind_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class TraceRecord final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:calf.proto.TraceRecord) */ {
 public:
  inline TraceRecord() : TraceRecord(nullptr) {}
  ~TraceRecord() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TraceRecord* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TraceRecord));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TraceRecord(::google::protobuf::internal::ConstantInitialized);

  inline TraceRecord(const TraceRecord& from) : TraceRecord(nullptr, from) {}
  inline TraceRecord(TraceRecord&& from) noexcept
      : TraceRecord(nullptr, ::std::move(from)) {}
  inline TraceRecord& operator=(const TraceRecord& from) {
    CopyFrom(from);
    return *this;
  }
  inline TraceRecord& operator=(TraceRecord&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TraceRecord& default_instance() {
    return *reinterpret_cast<const TraceRecord*>(
        &_TraceRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TraceRecord& a, TraceRecord& b) { a.Swap(&b); }
  inline void Swap(TraceRecord* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TraceRecord* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TraceRecord* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TraceRecord>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TraceRecord& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TraceRecord& from) { TraceRecord::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TraceRecord* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "calf.proto.TraceRecord"; }

 protected:
  explicit TraceRecord(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TraceRecord(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TraceRecord& from);
  TraceRecord(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TraceRecord&& from) noexcept
      : TraceRecord(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Kind = TraceRecord_Kind;
  static constexpr Kind SCOPE_ENTER = TraceRecord_Kind_SCOPE_ENTER;
  static constexpr Kind EVENT = TraceRecord_Kind_EVENT;
  static constexpr Kind SCOPE_EXIT = TraceRecord_Kind_SCOPE_EXIT;
  static inline bool Kind_IsValid(int value) {
    return TraceRecord_Kind_IsValid(value);
  }
  static constexpr Kind Kind_MIN = TraceRecord_Kind_Kind_MIN;
  static constexpr Kind Kind_MAX = TraceRecord_Kind_Kind_MAX;
  static constexpr int Kind_ARRAYSIZE = TraceRecord_Kind_Kind_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Kind_descriptor() {
    return TraceRecord_Kind_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Kind_Name(T value) {
    return TraceRecord_Kind_Name(value);
  }
  static inline bool Kind_Parse(
      ::absl::string_view name, Kind* PROTOBUF_NONNULL value) {
    return TraceRecord_Kind_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kInvokerFieldNumber = 5,
    kFileFieldNumber = 6,
    kArgsFieldNumber = 8,
    kTimestampMsFieldNumber = 1,
    kScopeIdFieldNumber = 2,
    kParentScopeIdFieldNumber = 3,
    kKindFieldNumber = 4,
    kLineFieldNumber = 7,
  };
  // string invoker = 5;
  void clear_invoker() ;
  const ::std::string& invoker() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_invoker(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_invoker();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_invoker();
  void set_allocated_invoker(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_invoker() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_invoker(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_invoker();

  public:
  // string file = 6;
  void clear_file() ;
  const ::std::string& file() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_file(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_file();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_file();
  void set_allocated_file(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_file() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_file(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_file();

  public:
  // string args = 8;
  void clear_args() ;
  const ::std::string& args() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_args(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_args();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_args();
  void set_allocated_args(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_args() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_args(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_args();

  public:
  // uint64 timestamp_ms = 1;
  void clear_timestamp_ms() ;
  ::uint64_t timestamp_ms() const;
  void set_timestamp_ms(::uint64_t value);

  private:
  ::uint64_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(::uint64_t value);

  public:
  // uint64 scope_id = 2;
  void clear_scope_id() ;
  ::uint64_t scope_id() const;
  void set_scope_id(::uint64_t value);

  private:
  ::uint64_t _internal_scope_id() const;
  void _internal_set_scope_id(::uint64_t value);

  public:
  // uint64 parent_scope_id = 3;
  void clear_parent_scope_id() ;
  ::uint64_t parent_scope_id() const;
  void set_parent_scope_id(::uint64_t value);

  private:
  ::uint64_t _internal_parent_scope_id() const;
  void _internal_set_parent_scope_id(::uint64_t value);

  public:
  // .calf.proto.TraceRecord.Kind kind = 4;
  void clear_kind() ;
  ::calf::proto::TraceRecord_Kind kind() const;
  void set_kind(::calf::proto::TraceRecord_Kind value);

  private:
  ::calf::proto::TraceRecord_Kind _internal_kind() const;
  void _internal_set_kind(::calf::proto::TraceRecord_Kind value);

  public:
  // uint32 line = 7;
  void clear_line() ;
  ::uint32_t line() const;
  void set_line(::uint32_t value);

  private:
  ::uint32_t _internal_line() const;
  void _internal_set_line(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:calf.proto.TraceRecord)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 54,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TraceRecord& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr invoker_;
    ::google::protobuf::internal::ArenaStringPtr file_;
    ::google::protobuf::internal::ArenaStringPtr args_;
    ::uint64_t timestamp_ms_;
    ::uint64_t scope_id_;
    ::uint64_t parent_scope_id_;
    int kind_;
    ::uint32_t line_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_calf_2fprotobuf_2fcalf_5ftrace_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TraceRecord_class_data_;
// -------------------------------------------------------------------

class TraceFile final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:calf.proto.TraceFile) */ {
 public:
  inline TraceFile() : TraceFile(nullptr) {}
  ~TraceFile() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TraceFile* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TraceFile));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TraceFile(::google::protobuf::internal::ConstantInitialized);

  inline TraceFile(const TraceFile& from) : TraceFile(nullptr, from) {}
  inline TraceFile(TraceFile&& from) noexcept
      : TraceFile(nullptr, ::std::move(from)) {}
  inline TraceFile& operator=(const TraceFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline TraceFile& operator=(TraceFile&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TraceFile& default_instance() {
    return *reinterpret_cast<const TraceFile*>(
        &_TraceFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TraceFile& a, TraceFile& b) { a.Swap(&b); }
  inline void Swap(TraceFile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TraceFile* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TraceFile* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TraceFile>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TraceFile& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TraceFile& from) { TraceFile::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TraceFile* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "calf.proto.TraceFile"; }

 protected:
  explicit TraceFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TraceFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TraceFile& from);
  TraceFile(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TraceFile&& from) noexcept
      : TraceFile(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRecordsFieldNumber = 1,
  };
  // repeated .calf.proto.TraceRecord records = 1;
  int records_size() const;
  private:
  int _internal_records_size() const;

  public:
  void clear_records() ;
  ::calf::proto::TraceRecord* PROTOBUF_NONNULL mutable_records(int index);
  ::google::protobuf::RepeatedPtrField<::calf::proto::TraceRecord>* PROTOBUF_NONNULL mutable_records();

  private:
  const ::google::protobuf::RepeatedPtrField<::calf::proto::TraceRecord>& _internal_records() const;
  ::google::protobuf::RepeatedPtrField<::calf::proto::TraceRecord>* PROTOBUF_NONNULL _internal_mutable_records();
  public:
  const ::calf::proto::TraceRecord& records(int index) const;
  ::calf::proto::TraceRecord* PROTOBUF_NONNULL add_records();
  const ::google::protobuf::RepeatedPtrField<::calf::proto::TraceRecord>& records() const;
  // @@protoc_insertion_point(class_scope:calf.proto.TraceFile)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TraceFile& from_msg);
    ::google::protobuf::RepeatedPtrField< ::calf::proto::TraceRecord > records_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_calf_2fprotobuf_2fcalf_5ftrace_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TraceFile_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TraceRecord

// uint64 timestamp_ms = 1;
inline void TraceRecord::clear_timestamp_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::uint64_t TraceRecord::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:calf.proto.TraceRecord.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void TraceRecord::set_timestamp_ms(::uint64_t value) {
  _internal_set_timestamp_ms(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:calf.proto.TraceRecord.timestamp_ms)
}
inline ::uint64_t TraceRecord::_internal_timestamp_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ms_;
}
inline void TraceRecord::_internal_set_timestamp_ms(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = value;
}

// uint64 scope_id = 2;
inline void TraceRecord::clear_scope_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scope_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::uint64_t TraceRecord::scope_id() const {
  // @@protoc_insertion_point(field_get:calf.proto.TraceRecord.scope_id)
  return _internal_scope_id();
}
inline void TraceRecord::set_scope_id(::uint64_t value) {
  _internal_set_scope_id(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:calf.proto.TraceRecord.scope_id)
}
inline ::uint64_t TraceRecord::_internal_scope_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scope_id_;
}
inline void TraceRecord::_internal_set_scope_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scope_id_ = value;
}

// uint64 parent_scope_id = 3;
inline void TraceRecord::clear_parent_scope_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parent_scope_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::uint64_t TraceRecord::parent_scope_id() const {
  // @@protoc_insertion_point(field_get:calf.proto.TraceRecord.parent_scope_id)
  return _internal_parent_scope_id();
}
inline void TraceRecord::set_parent_scope_id(::uint64_t value) {
  _internal_set_parent_scope_id(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:calf.proto.TraceRecord.parent_scope_id)
}
inline ::uint64_t TraceRecord::_internal_parent_scope_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.parent_scope_id_;
}
inline void TraceRecord::_internal_set_parent_scope_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parent_scope_id_ = value;
}

// .calf.proto.TraceRecord.Kind kind = 4;
inline void TraceRecord::clear_kind() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.kind_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::calf::proto::TraceRecord_Kind TraceRecord::kind() const {
  // @@protoc_insertion_point(field_get:calf.proto.TraceRecord.kind)
  return _internal_kind();
}
inline void TraceRecord::set_kind(::calf::proto::TraceRecord_Kind value) {
  _internal_set_kind(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:calf.proto.TraceRecord.kind)
}
inline ::calf::proto::TraceRecord_Kind TraceRecord::_internal_kind() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::calf::proto::TraceRecord_Kind>(_impl_.kind_);
}
inline void TraceRecord::_internal_set_kind(::calf::proto::TraceRecord_Kind value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.kind_ = value;
}

// string invoker = 5;
inline void TraceRecord::clear_invoker() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.invoker_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& TraceRecord::invoker() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:calf.proto.TraceRecord.invoker)
  return _internal_invoker();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TraceRecord::set_invoker(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.invoker_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:calf.proto.TraceRecord.invoker)
}
inline ::std::string* PROTOBUF_NONNULL TraceRecord::mutable_invoker()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_invoker();
  // @@protoc_insertion_point(field_mutable:calf.proto.TraceRecord.invoker)
  return _s;
}
inline const ::std::string& TraceRecord::_internal_invoker() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.invoker_.Get();
}
inline void TraceRecord::_internal_set_invoker(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.invoker_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TraceRecord::_internal_mutable_invoker() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.invoker_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TraceRecord::release_invoker() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:calf.proto.TraceRecord.invoker)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.invoker_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.invoker_.Set("", GetArena());
  }
  return released;
}
inline void TraceRecord::set_allocated_invoker(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.invoker_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.invoker_.IsDefault()) {
    _impl_.invoker_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:calf.proto.TraceRecord.invoker)
}

// string file = 6;
inline void TraceRecord::clear_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& TraceRecord::file() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:calf.proto.TraceRecord.file)
  return _internal_file();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TraceRecord::set_file(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.file_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:calf.proto.TraceRecord.file)
}
inline ::std::string* PROTOBUF_NONNULL TraceRecord::mutable_file()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_file();
  // @@protoc_insertion_point(field_mutable:calf.proto.TraceRecord.file)
  return _s;
}
inline const ::std::string& TraceRecord::_internal_file() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_.Get();
}
inline void TraceRecord::_internal_set_file(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.file_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TraceRecord::_internal_mutable_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.file_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TraceRecord::release_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:calf.proto.TraceRecord.file)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.file_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.file_.Set("", GetArena());
  }
  return released;
}
inline void TraceRecord::set_allocated_file(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.file_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.file_.IsDefault()) {
    _impl_.file_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:calf.proto.TraceRecord.file)
}

// uint32 line = 7;
inline void TraceRecord::clear_line() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.line_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::uint32_t TraceRecord::line() const {
  // @@protoc_insertion_point(field_get:calf.proto.TraceRecord.line)
  return _internal_line();
}
inline void TraceRecord::set_line(::uint32_t value) {
  _internal_set_line(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:calf.proto.TraceRecord.line)
}
inline ::uint32_t TraceRecord::_internal_line() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.line_;
}
inline void TraceRecord::_internal_set_line(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.line_ = value;
}

// string args = 8;
inline void TraceRecord::clear_args() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.args_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::std::string& TraceRecord::args() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:calf.proto.TraceRecord.args)
  return _internal_args();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TraceRecord::set_args(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.args_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:calf.proto.TraceRecord.args)
}
inline ::std::string* PROTOBUF_NONNULL TraceRecord::mutable_args()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_args();
  // @@protoc_insertion_point(field_mutable:calf.proto.TraceRecord.args)
  return _s;
}
inline const ::std::string& TraceRecord::_internal_args() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.args_.Get();
}
inline void TraceRecord::_internal_set_args(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.args_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TraceRecord::_internal_mutable_args() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.args_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TraceRecord::release_args() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:calf.proto.TraceRecord.args)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.args_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.args_.Set("", GetArena());
  }
  return released;
}
inline void TraceRecord::set_allocated_args(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.args_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.args_.IsDefault()) {
    _impl_.args_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:calf.proto.TraceRecord.args)
}

// -------------------------------------------------------------------

// TraceFile

// repeated .calf.proto.TraceRecord records = 1;
inline int TraceFile::_internal_records_size() const {
  return _internal_records().size();
}
inline int TraceFile::records_size() const {
  return _internal_records_size();
}
inline void TraceFile::clear_records() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.records_.Clear();
}
inline ::calf::proto::TraceRecord* PROTOBUF_NONNULL TraceFile::mutable_records(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:calf.proto.TraceFile.records)
  return _internal_mutable_records()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::calf::proto::TraceRecord>* PROTOBUF_NONNULL TraceFile::mutable_records()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:calf.proto.TraceFile.records)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_records();
}
inline const ::calf::proto::TraceRecord& TraceFile::records(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:calf.proto.TraceFile.records)
  return _internal_records().Get(index);
}
inline ::calf::proto::TraceRecord* PROTOBUF_NONNULL TraceFile::add_records()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::calf::proto::TraceRecord* _add = _internal_mutable_records()->Add();
  // @@protoc_insertion_point(field_add:calf.proto.TraceFile.records)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::calf::proto::TraceRecord>& TraceFile::records() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:calf.proto.TraceFile.records)
  return _internal_records();
}
inline const ::google::protobuf::RepeatedPtrField<::calf::proto::TraceRecord>&
TraceFile::_internal_records() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.records_;
}
inline ::google::protobuf::RepeatedPtrField<::calf::proto::TraceRecord>* PROTOBUF_NONNULL
TraceFile::_internal_mutable_records() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.records_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace calf


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::calf::proto::TraceRecord_Kind> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::calf::proto::TraceRecord_Kind>() {
  return ::calf::proto::TraceRecord_Kind_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // calf_2fprotobuf_2fcalf_5ftrace_2eproto_2epb_2eh
