// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calf/protobuf/calf_trace.proto
// Protobuf C++ Version: 6.31.1

#include "calf/protobuf/calf_trace.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace calf {
namespace proto {

inline constexpr TraceRecord::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        invoker_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        file_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        args_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_ms_{::uint64_t{0u}},
        scope_id_{::uint64_t{0u}},
        parent_scope_id_{::uint64_t{0u}},
        kind_{static_cast< ::calf::proto::TraceRecord_Kind >(0)},
        line_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR TraceRecord::TraceRecord(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TraceRecord_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TraceRecordDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TraceRecordDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TraceRecordDefaultTypeInternal() {}
  union {
    TraceRecord _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TraceRecordDefaultTypeInternal _TraceRecord_default_instance_;

inline constexpr TraceFile::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : records_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TraceFile::TraceFile(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TraceFile_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TraceFileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TraceFileDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TraceFileDefaultTypeInternal() {}
  union {
    TraceFile _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TraceFileDefaultTypeInternal _TraceFile_default_instance_;
}  // namespace proto
}  // namespace calf
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_calf_2fprotobuf_2fcalf_5ftrace_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_calf_2fprotobuf_2fcalf_5ftrace_2eproto = nullptr;
const ::uint32_t
    TableStruct_calf_2fprotobuf_2fcalf_5ftrace_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::calf::proto::TraceRecord, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::calf::proto::TraceRecord, _impl_.timestamp_ms_),
        PROTOBUF_FIELD_OFFSET(::calf::proto::TraceRecord, _impl_.scope_id_),
        PROTOBUF_FIELD_OFFSET(::calf::proto::TraceRecord, _impl_.parent_scope_id_),
        PROTOBUF_FIELD_OFFSET(::calf::proto::TraceRecord, _impl_.kind_),
        PROTOBUF_FIELD_OFFSET(::calf::proto::TraceRecord, _impl_.invoker_),
        PROTOBUF_FIELD_OFFSET(::calf::proto::TraceRecord, _impl_.file_),
        PROTOBUF_FIELD_OFFSET(::calf::proto::TraceRecord, _impl_.line_),
        PROTOBUF_FIELD_OFFSET(::calf::proto::TraceRecord, _impl_.args_),
        3,
        4,
        5,
        6,
        0,
        1,
        7,
        2,
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::calf::proto::TraceFile, _impl_.records_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::calf::proto::TraceRecord)},
        {19, sizeof(::calf::proto::TraceFile)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::calf::proto::_TraceRecord_default_instance_._instance,
    &::calf::proto::_TraceFile_default_instance_._instance,
};
const char descriptor_table_protodef_calf_2fprotobuf_2fcalf_5ftrace_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\036calf/protobuf/calf_trace.proto\022\ncalf.p"
    "roto\"\351\001\n\013TraceRecord\022\024\n\014timestamp_ms\030\001 \001"
    "(\004\022\020\n\010scope_id\030\002 \001(\004\022\027\n\017parent_scope_id\030"
    "\003 \001(\004\022*\n\004kind\030\004 \001(\0162\034.calf.proto.TraceRe"
    "cord.Kind\022\017\n\007invoker\030\005 \001(\t\022\014\n\004file\030\006 \001(\t"
    "\022\014\n\004line\030\007 \001(\r\022\014\n\004args\030\010 \001(\t\"2\n\004Kind\022\017\n\013"
    "SCOPE_ENTER\020\000\022\t\n\005EVENT\020\001\022\016\n\nSCOPE_EXIT\020\002"
    "\"5\n\tTraceFile\022(\n\007records\030\001 \003(\0132\027.calf.pr"
    "oto.TraceRecordb\006proto3"
};
static ::absl::once_flag descriptor_table_calf_2fprotobuf_2fcalf_5ftrace_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_calf_2fprotobuf_2fcalf_5ftrace_2eproto = {
    false,
    false,
    343,
    descriptor_table_protodef_calf_2fprotobuf_2fcalf_5ftrace_2eproto,
    "calf/protobuf/calf_trace.proto",
    &descriptor_table_calf_2fprotobuf_2fcalf_5ftrace_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_calf_2fprotobuf_2fcalf_5ftrace_2eproto::offsets,
    file_level_enum_descriptors_calf_2fprotobuf_2fcalf_5ftrace_2eproto,
    file_level_service_descriptors_calf_2fprotobuf_2fcalf_5ftrace_2eproto,
};
namespace calf {
namespace proto {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL TraceRecord_Kind_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_calf_2fprotobuf_2fcalf_5ftrace_2eproto);
  return file_level_enum_descriptors_calf_2fprotobuf_2fcalf_5ftrace_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t TraceRecord_Kind_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class TraceRecord::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TraceRecord>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_._has_bits_);
};

TraceRecord::TraceRecord(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TraceRecord_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calf.proto.TraceRecord)
}
PROTOBUF_NDEBUG_INLINE TraceRecord::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::calf::proto::TraceRecord& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        invoker_(arena, from.invoker_),
        file_(arena, from.file_),
        args_(arena, from.args_) {}

TraceRecord::TraceRecord(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TraceRecord& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TraceRecord_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TraceRecord* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_ms_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, timestamp_ms_),
           offsetof(Impl_, line_) -
               offsetof(Impl_, timestamp_ms_) +
               sizeof(Impl_::line_));

  // @@protoc_insertion_point(copy_constructor:calf.proto.TraceRecord)
}
PROTOBUF_NDEBUG_INLINE TraceRecord::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        invoker_(arena),
        file_(arena),
        args_(arena) {}

inline void TraceRecord::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_ms_),
           0,
           offsetof(Impl_, line_) -
               offsetof(Impl_, timestamp_ms_) +
               sizeof(Impl_::line_));
}
TraceRecord::~TraceRecord() {
  // @@protoc_insertion_point(destructor:calf.proto.TraceRecord)
  SharedDtor(*this);
}
inline void TraceRecord::SharedDtor(MessageLite& self) {
  TraceRecord& this_ = static_cast<TraceRecord&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.invoker_.Destroy();
  this_._impl_.file_.Destroy();
  this_._impl_.args_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TraceRecord::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TraceRecord(arena);
}
constexpr auto TraceRecord::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TraceRecord),
                                            alignof(TraceRecord));
}
constexpr auto TraceRecord::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TraceRecord_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TraceRecord::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TraceRecord>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TraceRecord::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TraceRecord>(), &TraceRecord::ByteSizeLong,
              &TraceRecord::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_._cached_size_),
          false,
      },
      &TraceRecord::kDescriptorMethods,
      &descriptor_table_calf_2fprotobuf_2fcalf_5ftrace_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TraceRecord_class_data_ =
        TraceRecord::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TraceRecord::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TraceRecord_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TraceRecord_class_data_.tc_table);
  return TraceRecord_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 54, 2>
TraceRecord::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TraceRecord_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calf::proto::TraceRecord>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string args = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 2, 0, PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.args_)}},
    // uint64 timestamp_ms = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TraceRecord, _impl_.timestamp_ms_), 3>(),
     {8, 3, 0, PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.timestamp_ms_)}},
    // uint64 scope_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TraceRecord, _impl_.scope_id_), 4>(),
     {16, 4, 0, PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.scope_id_)}},
    // uint64 parent_scope_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TraceRecord, _impl_.parent_scope_id_), 5>(),
     {24, 5, 0, PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.parent_scope_id_)}},
    // .calf.proto.TraceRecord.Kind kind = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TraceRecord, _impl_.kind_), 6>(),
     {32, 6, 0, PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.kind_)}},
    // string invoker = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 0, 0, PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.invoker_)}},
    // string file = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 1, 0, PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.file_)}},
    // uint32 line = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TraceRecord, _impl_.line_), 7>(),
     {56, 7, 0, PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.line_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 timestamp_ms = 1;
    {PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.timestamp_ms_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 scope_id = 2;
    {PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.scope_id_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 parent_scope_id = 3;
    {PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.parent_scope_id_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // .calf.proto.TraceRecord.Kind kind = 4;
    {PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.kind_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string invoker = 5;
    {PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.invoker_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string file = 6;
    {PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.file_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 line = 7;
    {PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.line_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // string args = 8;
    {PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.args_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\0\0\0\0\7\4\0\4\0\0\0\0\0\0\0"
    "calf.proto.TraceRecord"
    "invoker"
    "file"
    "args"
  }},
};
PROTOBUF_NOINLINE void TraceRecord::Clear() {
// @@protoc_insertion_point(message_clear_start:calf.proto.TraceRecord)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.invoker_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.file_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _impl_.args_.ClearNonDefaultToEmpty();
    }
  }
  if ((cached_has_bits & 0x000000f8u) != 0) {
    ::memset(&_impl_.timestamp_ms_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.line_) -
        reinterpret_cast<char*>(&_impl_.timestamp_ms_)) + sizeof(_impl_.line_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TraceRecord::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TraceRecord& this_ = static_cast<const TraceRecord&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TraceRecord::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TraceRecord& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:calf.proto.TraceRecord)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 timestamp_ms = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (this_._internal_timestamp_ms() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_timestamp_ms(), target);
    }
  }

  // uint64 scope_id = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (this_._internal_scope_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_scope_id(), target);
    }
  }

  // uint64 parent_scope_id = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000020u) != 0) {
    if (this_._internal_parent_scope_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          3, this_._internal_parent_scope_id(), target);
    }
  }

  // .calf.proto.TraceRecord.Kind kind = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000040u) != 0) {
    if (this_._internal_kind() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_kind(), target);
    }
  }

  // string invoker = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_invoker().empty()) {
      const ::std::string& _s = this_._internal_invoker();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "calf.proto.TraceRecord.invoker");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  // string file = 6;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_file().empty()) {
      const ::std::string& _s = this_._internal_file();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "calf.proto.TraceRecord.file");
      target = stream->WriteStringMaybeAliased(6, _s, target);
    }
  }

  // uint32 line = 7;
  if ((this_._impl_._has_bits_[0] & 0x00000080u) != 0) {
    if (this_._internal_line() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          7, this_._internal_line(), target);
    }
  }

  // string args = 8;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (!this_._internal_args().empty()) {
      const ::std::string& _s = this_._internal_args();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "calf.proto.TraceRecord.args");
      target = stream->WriteStringMaybeAliased(8, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calf.proto.TraceRecord)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TraceRecord::ByteSizeLong(const MessageLite& base) {
  const TraceRecord& this_ = static_cast<const TraceRecord&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TraceRecord::ByteSizeLong() const {
  const TraceRecord& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:calf.proto.TraceRecord)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    // string invoker = 5;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_invoker().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_invoker());
      }
    }
    // string file = 6;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_file().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_file());
      }
    }
    // string args = 8;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!this_._internal_args().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_args());
      }
    }
    // uint64 timestamp_ms = 1;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (this_._internal_timestamp_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_timestamp_ms());
      }
    }
    // uint64 scope_id = 2;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (this_._internal_scope_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_scope_id());
      }
    }
    // uint64 parent_scope_id = 3;
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (this_._internal_parent_scope_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_parent_scope_id());
      }
    }
    // .calf.proto.TraceRecord.Kind kind = 4;
    if ((cached_has_bits & 0x00000040u) != 0) {
      if (this_._internal_kind() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_kind());
      }
    }
    // uint32 line = 7;
    if ((cached_has_bits & 0x00000080u) != 0) {
      if (this_._internal_line() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_line());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TraceRecord::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TraceRecord*>(&to_msg);
  auto& from = static_cast<const TraceRecord&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calf.proto.TraceRecord)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_invoker().empty()) {
        _this->_internal_set_invoker(from._internal_invoker());
      } else {
        if (_this->_impl_.invoker_.IsDefault()) {
          _this->_internal_set_invoker("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_file().empty()) {
        _this->_internal_set_file(from._internal_file());
      } else {
        if (_this->_impl_.file_.IsDefault()) {
          _this->_internal_set_file("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!from._internal_args().empty()) {
        _this->_internal_set_args(from._internal_args());
      } else {
        if (_this->_impl_.args_.IsDefault()) {
          _this->_internal_set_args("");
        }
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (from._internal_timestamp_ms() != 0) {
        _this->_impl_.timestamp_ms_ = from._impl_.timestamp_ms_;
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (from._internal_scope_id() != 0) {
        _this->_impl_.scope_id_ = from._impl_.scope_id_;
      }
    }
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (from._internal_parent_scope_id() != 0) {
        _this->_impl_.parent_scope_id_ = from._impl_.parent_scope_id_;
      }
    }
    if ((cached_has_bits & 0x00000040u) != 0) {
      if (from._internal_kind() != 0) {
        _this->_impl_.kind_ = from._impl_.kind_;
      }
    }
    if ((cached_has_bits & 0x00000080u) != 0) {
      if (from._internal_line() != 0) {
        _this->_impl_.line_ = from._impl_.line_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TraceRecord::CopyFrom(const TraceRecord& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calf.proto.TraceRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TraceRecord::InternalSwap(TraceRecord* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.invoker_, &other->_impl_.invoker_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_, &other->_impl_.file_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.args_, &other->_impl_.args_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.line_)
      + sizeof(TraceRecord::_impl_.line_)
      - PROTOBUF_FIELD_OFFSET(TraceRecord, _impl_.timestamp_ms_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_ms_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_ms_));
}

::google::protobuf::Metadata TraceRecord::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TraceFile::_Internal {
 public:
};

TraceFile::TraceFile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TraceFile_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calf.proto.TraceFile)
}
PROTOBUF_NDEBUG_INLINE TraceFile::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::calf::proto::TraceFile& from_msg)
      : records_{visibility, arena, from.records_},
        _cached_size_{0} {}

TraceFile::TraceFile(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TraceFile& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TraceFile_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TraceFile* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:calf.proto.TraceFile)
}
PROTOBUF_NDEBUG_INLINE TraceFile::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : records_{visibility, arena},
        _cached_size_{0} {}

inline void TraceFile::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TraceFile::~TraceFile() {
  // @@protoc_insertion_point(destructor:calf.proto.TraceFile)
  SharedDtor(*this);
}
inline void TraceFile::SharedDtor(MessageLite& self) {
  TraceFile& this_ = static_cast<TraceFile&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TraceFile::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TraceFile(arena);
}
constexpr auto TraceFile::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TraceFile, _impl_.records_) +
          decltype(TraceFile::_impl_.records_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(TraceFile), alignof(TraceFile), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TraceFile::PlacementNew_,
                                 sizeof(TraceFile),
                                 alignof(TraceFile));
  }
}
constexpr auto TraceFile::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TraceFile_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TraceFile::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TraceFile>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TraceFile::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TraceFile>(), &TraceFile::ByteSizeLong,
              &TraceFile::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TraceFile, _impl_._cached_size_),
          false,
      },
      &TraceFile::kDescriptorMethods,
      &descriptor_table_calf_2fprotobuf_2fcalf_5ftrace_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TraceFile_class_data_ =
        TraceFile::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TraceFile::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TraceFile_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TraceFile_class_data_.tc_table);
  return TraceFile_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
TraceFile::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    TraceFile_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calf::proto::TraceFile>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .calf.proto.TraceRecord records = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TraceFile, _impl_.records_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .calf.proto.TraceRecord records = 1;
    {PROTOBUF_FIELD_OFFSET(TraceFile, _impl_.records_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::calf::proto::TraceRecord>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void TraceFile::Clear() {
// @@protoc_insertion_point(message_clear_start:calf.proto.TraceFile)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.records_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TraceFile::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TraceFile& this_ = static_cast<const TraceFile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TraceFile::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TraceFile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:calf.proto.TraceFile)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .calf.proto.TraceRecord records = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_records_size());
       i < n; i++) {
    const auto& repfield = this_._internal_records().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calf.proto.TraceFile)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TraceFile::ByteSizeLong(const MessageLite& base) {
  const TraceFile& this_ = static_cast<const TraceFile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TraceFile::ByteSizeLong() const {
  const TraceFile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:calf.proto.TraceFile)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .calf.proto.TraceRecord records = 1;
    {
      total_size += 1UL * this_._internal_records_size();
      for (const auto& msg : this_._internal_records()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TraceFile::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TraceFile*>(&to_msg);
  auto& from = static_cast<const TraceFile&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calf.proto.TraceFile)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_records()->MergeFrom(
      from._internal_records());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TraceFile::CopyFrom(const TraceFile& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calf.proto.TraceFile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TraceFile::InternalSwap(TraceFile* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.records_.InternalSwap(&other->_impl_.records_);
}

::google::protobuf::Metadata TraceFile::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace calf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_calf_2fprotobuf_2fcalf_5ftrace_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
